CREATE TABLE [dbo].[MAYIN] (
  [MASP] [varchar](10) NOT NULL,
  [LOAI] [bit] NOT NULL,
  [PHUONGPHAPIN] [tinyint] NOT NULL,
  [MUC_RIBBON] [bit] NOT NULL,
  [MUC_NHUOM] [bit] NOT NULL,
  [MUC_NUOC] [bit] NOT NULL,
  [MUC_BOT] [bit] NOT NULL,
  [MUC_DAU] [bit] NOT NULL,
  [MUC_DAC] [bit] NOT NULL,
  [GIAY_FORD] [bit] NOT NULL,
  [GIAY_COUCHE] [bit] NOT NULL,
  [GIAY_BRISTOL] [bit] NOT NULL,
  [GIAY_DUPLEX] [bit] NOT NULL,
  [GIAY_DECAL] [bit] NOT NULL,
  [GIAY_KRAFT] [bit] NOT NULL,
  [GIAY_IVORNY] [bit] NOT NULL,
  [KETNOI_USBA] [bit] NOT NULL,
  [KETNOI_USBB] [bit] NOT NULL,
  [KETNOI_ENTERNET] [bit] NOT NULL,
  [KETNOI_WIRELESS] [bit] NOT NULL,
  [HDH_WIN] [bit] NOT NULL,
  [HDH_IOS] [bit] NOT NULL,
  [HDH_LINUX] [bit] NOT NULL,
  [HDH_ANDROID] [bit] NOT NULL,
  CONSTRAINT [PK_MAYIN] PRIMARY KEY CLUSTERED ([MASP])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[MAYIN]
  ADD CONSTRAINT [FK_MAYIN_PHUONGPHAPIN] FOREIGN KEY ([PHUONGPHAPIN]) REFERENCES [dbo].[PHUONGPHAPIN] ([PP])
GO

ALTER TABLE [dbo].[MAYIN]
  ADD CONSTRAINT [FK_MAYIN_SANPHAM] FOREIGN KEY ([MASP]) REFERENCES [dbo].[SANPHAM] ([MASP]) ON DELETE CASCADE ON UPDATE CASCADE
GO