CREATE TABLE [dbo].[LOGHIST] (
  [USERNAME] [nchar](20) NOT NULL,
  [LOGIN] [datetime] NOT NULL,
  CONSTRAINT [PK_LOGHIST] PRIMARY KEY CLUSTERED ([USERNAME], [LOGIN])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[LOGHIST]
  ADD CONSTRAINT [FK_LOGHIST_USER] FOREIGN KEY ([USERNAME]) REFERENCES [dbo].[USERDB] ([USERNAME])
GO