CREATE TABLE [dbo].[USERDB] (
  [USERNAME] [nchar](20) NOT NULL,
  [PASSWORD] [nchar](10) NOT NULL,
  [CHUCVU] [tinyint] NOT NULL CONSTRAINT [DF_USER_ADMIN] DEFAULT (0),
  CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED ([USERNAME])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[USERDB]
  ADD CONSTRAINT [FK_USERDB_CHUCVU] FOREIGN KEY ([CHUCVU]) REFERENCES [dbo].[CHUCVU] ([CHUCVU])
GO