--
-- Script was generated by Devart dbForge Data Pump for SQL Server, Version 1.8.13.0
-- Product home page: http://www.devart.com/dbforge/sql/data-pump
-- Script date 26/11/2022 7:31:18 SA
-- Server version: 14.00.2042
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT QLKMI.dbo.CHUCVU(CHUCVU, TENCV) VALUES (0, N'Nhân viên ')
INSERT QLKMI.dbo.CHUCVU(CHUCVU, TENCV) VALUES (1, N'Nhân viên quản lý xuất hàng')
INSERT QLKMI.dbo.CHUCVU(CHUCVU, TENCV) VALUES (2, N'Nhân viên quản lý nhập hàng')
INSERT QLKMI.dbo.CHUCVU(CHUCVU, TENCV) VALUES (3, N'Nhân viên quản lý (ADMIN)')
GO